Report_date: #报告的日期
  year:  
  month: 
  day:   

ZHFLOW_KEYWORDS: # 关键词在数据库中的名称
  开户日期: 开户日期
  销户日期: 销户日期
  账户状态: 账户状态
  账户余额时间: 余额时间
  账户余额: 折算金额
  是否境内账户: 是否境外账户

ZHFLOW_TYPE:
  - 开户申请
  - 变更申请

BANKTYPE:
  - 财务公司
  - 合作银行
  - 非合作银行

SHOWCOLUMNS_BANK_ACCOUNT_INFO:
  #  - 单位名称
  - 账户名称
  - 银行账号 
  - 账户性质
  - 金融机构
  - 所属子集团名称
  - 开户机构
  - 银行城市
  - 国家/地区
  - 是否境外账户

ZHFLOW_STAGES:
  "A": "正在审批"
  "B": "已签章，待补录信息"
  "C": "办理完成"

ZHFLOW_TASKNAMES:
  "A": "经办"
  "B1": "复核1"
  "B2": "复核1"
  "C1": "审批1"
  "D1": "财务金融部"
  "D2": "财务金融部处室领导"
  "E": "集团公司总会计师"
  "F": "司库直联接口"
  "Z": "补录"


VARIES_CWGS_ACCOUNTS_TYPES_INCLUDE: &BankAccountType0 # 财务公司账户性质分类
  - 基建项目存款
  - 集团结算存款
  - 科研项目存款
  - 临时存款
  - 买方信贷保证金存款
  - 母子联动存款
  - 一般保证金存款
  - 电商资金池
  - 一天
  - 七天
  - 一个月
  - 三个月
  - 六个月
  - 一年
  - 两年
  - 三年
  - 五年
  - 其它存款

VARIES_BANK_ACCOUNTS_TYPES_INCLUDE: &BankAccountType1 # 账户性质计算数量
  - 保证金户-保函
  - 保证金户-票据
  - 保证金户-其它
  - 保证金户-信用证
  - 基本账户-非收支分线基本户
  - 基本账户-收支分线基本支出户
  - 境外账户-结算账户
  - 境外账户-融资账户
  - 其他账户
  - 融资账户
  - 收入账户
  - 同业账户-活期
  - 同业账户-人行准备金
  - 外币账户
  - 支出账户
  - 专项账户-处僵治困、三供一业专户
  - 专项账户-第三方支付平台账户
  - 专项账户-纳税专户
  - 专项账户-农民工工资账户
  - 专项账户-其他专项账户
  - 专项账户-上市公司募集资金专户
  - 专项账户-项目专户
  - 专项账户-债券募集资金专户

# 账户性质不计算账户数量 但是计算余额
VARIES_BANK_ACCOUNTS_TYPES_NOTINCLUDE_COUNT: &BankAccountType2
  - 保证金户-虚拟户
  - 同业账户-定期
  - 同业账户-同业存单
  - 专项账户-财政零余额账户

# 账户性质不计算账户数量 也不计算余额
VARIES_BANK_ACCOUNTS_TYPES_NOTINCLUDE_AMOUNT: &BankAccountType3
  - 特殊账户-党费账户
  - 特殊账户-工会账户
  - 特殊账户-住房公积金账户
  - 专项账户-住房类账户

VARIES_BANK_ACCOUNTS_TYPES: # 所有账户性质 #注意为列表镶嵌
  - *BankAccountType1
  - *BankAccountType2
  - *BankAccountType3

ACCOUNT_IN_MAINLAND_OFFSHORE:
  - 境内
  - 境外


VARIES_BANK_TYPE1_NAMES: &BankType1 # 合作银行名录
  - 国家开发银行
  - 中国进出口银行
  - 中国工商银行
  - 中国农业银行
  - 中国银行
  - 中国建设银行
  - 交通银行
  - 中国邮政储蓄银行
  - 中信银行
  - 中国光大银行
  - 招商银行
  - 上海浦东发展银行
  - 中国民生银行
  - 华夏银行
  - 平安银行
  - 兴业银行
  - 广发银行
  - 渤海银行
  - 浙商银行
  - 星展银行
  - 大华银行
  - 华侨银行

VARIES_BGSUBGROUP_SHORTNAMES:
  - 兵科院
  - 北方公司
  - 北化研究院集团（217所）
  - 物资集团
  - 财务公司
  - 201所（兵器一院）
  - 202所（兵器二院）
  - 203所（兵器三院）
  - 204所（兵器四院）
  - 导控所
  - 北斗院
  - 创新院
  - 动力院
  - 引信院
  - 特能集团
  - 材料院
  - 光电集团
  - 信息院集团
  - 导航集团
  - 夜视院集团
  - 激光院
  - 电子院
  - 微电子院
  - 爱生集团
  - 中兵投资
  - 一机集团
  - 哈一机集团
  - 和平重工集团
  - 北重集团
  - 凌云集团
  - 北方车辆集团
  - 江麓集团
  - 铁马集团
  - 江山重工研究院
  - 武重集团
  - 北奔重汽
  - 晋西集团
  - 豫西集团
  - 辽沈集团
  - 淮海集团
  - 西北工业集团
  - 东北工业集团
  - 华安集团
  - 江南工业集团
  - 航弹院
  - 山东工业集团
  - 吉林江机
  - 华锦集团
  - 规划院
  - 信息中心
  - 五洲设计院
  - 北方设计院
  - 试验院
  - 人才院
  - 210所（科技咨询与标准院）
  - 置业集团
  - 北方投资公司
  - 节能环保公司
  - 档案馆

VARIES_BGSUBGROUP_FULLNAMES:
  - 中国兵器科学研究院
  - 中国北方工业有限公司
  - 中国北方化学研究院集团有限公司
  - 中国兵工物资集团有限公司
  - 兵工财务有限责任公司
  - 中国北方车辆研究所
  - 西北机电工程研究所
  - 西安现代控制技术研究所
  - 西安近代化学研究所
  - 中国兵器工业导航与控制技术研究所
  - 北斗应用发展研究院
  - 中兵智能创新研究院有限公司
  - 中国兵器工业集团动力研究院有限公司
  - 中国兵器工业集团引信研究院有限公司
  - 北方特种能源集团有限公司
  - 北方材料科学与工程研究院有限公司
  - 北方光电集团有限公司
  - 北方信息控制研究院集团有限公司
  - 北方导航科技集团有限公司
  - 北方夜视科技研究院集团有限公司
  - 北方激光研究院有限公司
  - 北方电子研究院有限公司
  - 安徽北方微电子研究院集团有限公司
  - 西安爱生技术集团有限公司
  - 中兵投资管理有限责任公司
  - 内蒙古第一机械集团有限公司
  - 哈尔滨第一机械集团有限公司
  - 齐齐哈尔和平重工集团有限公司
  - 内蒙古北方重工业集团有限公司
  - 北方凌云工业集团有限公司
  - 北京北方车辆集团有限公司
  - 江麓机电集团有限公司
  - 重庆铁马工业集团有限公司
  - 中国兵器工业集团江山重工研究院有限公司
  - 武汉重型机床集团有限公司
  - 北奔重型汽车集团有限公司
  - 晋西工业集团有限责任公司
  - 豫西工业集团有限公司
  - 辽沈工业集团有限公司
  - 淮海工业集团有限公司
  - 西北工业集团有限公司
  - 东北工业集团有限公司
  - 北方华安工业集团有限公司
  - 江南工业集团有限公司
  - 中国兵器工业集团航空弹药研究院有限公司
  - 山东特种工业集团有限公司
  - 吉林江机特种工业有限公司
  - 北方华锦化学工业集团有限公司
  - 中国兵器工业规划研究院
  - 中国兵器工业信息中心
  - 中国五洲工程设计集团有限公司
  - 北方工程设计研究院有限公司
  - 中国兵器工业试验测试研究院
  - 中国兵器人才研究院
  - 中国兵器科技咨询与标准研究院
  - 北方置业集团有限公司
  - 北方发展投资有限公司
  - 中兵节能环保集团有限公司
  - 中国兵器工业档案馆
